# https://aka.ms/yaml
# Azure DevOps Pipeline with Synopsys IO

trigger:
  branches:
    include:
      - main
      - devsecops

pool:
  name: Custom

- stage: Prescription
  jobs:
  - job: PrescriptionJob
    displayName: IO - Prescription
    timeoutInMinutes: 0
    steps:
    - checkout: none
    - script: |
        pwd
        ls -ltr
