# https://aka.ms/yaml
# Azure DevOps Pipeline with Synopsys IO

trigger:
  branches:
    include:
      - main
      - devsecops

pool:
  name: Custom

variables:
  # IO
  PERSONA: devsecops
  PROJECT_NAME: WebGoat
  WORKFLOW_VERSION: 2022.7.0

  # JIRA
  JIRA_ASSIGNEE: ''
  JIRA_ISSUE_TYPE: Bug
  JIRA_ISSUE_QUERY: "resolution=Unresolved"
  JIRA_PROJECT_KEY: ''
  JIRA_PROJECT_NAME: ''

stages:
- stage: IntelligentOrchestration
  jobs:
  - job: IntelligentOrchestration
    displayName: IntelligentOrchestration
    timeoutInMinutes: 0
    steps:
    - checkout: self
    - script: |
        # Get SCM details
        SCM_TYPE=$(echo "$(Build.Repository.Provider)" | awk '{print tolower($0)}')
        SCM_OWNER="$(cut -d'/' -f1 <<<"$(Build.Repository.Name)")"
        SCM_REPO_NAME="$(cut -d'/' -f2 <<<"$(Build.Repository.Name)")"
        SCM_BRANCH_NAME=$(Build.SourceBranchName)
        
        # Stage IO (Prescription)
        ../../../io --stage io \
          io.server.url="https://io03.codedx.synopsys.com" \
          io.server.token=$(IO_TOKEN) \
          workflow.engine.version=$(WORKFLOW_VERSION) \
          project.name=$(PROJECT_NAME) \
          persona.type=$(PERSONA) \
          scm.type="$SCM_TYPE" \
          scm.owner="$SCM_OWNER" \
          scm.repository.name="$SCM_REPO_NAME" \
          scm.repository.branch.name="$SCM_BRANCH_NAME" \
          github.apiurl="https://api.github.com/repos" \
          github.username=$(GITHUB_USERNAME) \
          github.token=$(GITHUB_TOKEN)
      displayName: 'Stage IO (Prescription)'

    - script: |
        #export SYNOPSYS_IO_Blackduck_AuthToken=$(BLACK_DUCK_TOKEN)
        #export SYNOPSYS_IO_Blackduck_ProjectName=WebGoat
        #export SYNOPSYS_IO_Blackduck_InstanceUrl="https://poc95.blackduck.synopsys.com"
        ../../../io --state io_state.json --stage execution --adapters io-adapter-blackduck.json \
          blackduck.instanceurl="https://poc95.blackduck.synopsys.com" \
          blackduck.authtoken=$(BLACK_DUCK_TOKEN) \
          blackduck.projectname="WebGoat" \
          blackduck.projectversion="8.2.1-SNAPSHOT" 
      displayName: 'Stage Execution (SCA - Black Duck)'
