# https://aka.ms/yaml
# Azure DevOps Pipeline with Synopsys IO

trigger:
  branches:
    include:
      - main
      - devsecops

pool:
  name: Custom

variables:
  # IO
  PERSONA: devsecops
  PROJECT_NAME: WebGoat

  # JIRA
  JIRA_ASSIGNEE: ''
  JIRA_ISSUE_TYPE: Bug
  JIRA_ISSUE_QUERY: "resolution=Unresolved"
  JIRA_PROJECT_KEY: ''
  JIRA_PROJECT_NAME: ''

  # AST - SCA - Black Duck
  BLACKDUCK_PROJECT_NAME: WebGoat
  BLACKDUCK_PROJECT_VERSION: 8.2.1-SNAPSHOT

stages:
- stage: Prescription
  jobs:
  - job: PrescriptionJob
    displayName: IO - Prescription
    timeoutInMinutes: 0
    steps:
    - checkout: none
    - script: |
        pwd
        SCM_TYPE=$(echo "$(Build.Repository.Provider)" | awk '{print tolower($0)}')
        SCM_OWNER="$(cut -d'/' -f1 <<<"$(Build.Repository.Name)")"
        SCM_REPO_NAME="$(cut -d'/' -f2 <<<"$(Build.Repository.Name)")"
        SCM_BRANCH_NAME=$(Build.SourceBranchName)
        
        echo "$(SCM_OWNER)"
        echo "$(SCM_REPO_NAME)"
        echo "$(SCM_TYPE)"
        echo "$(SCM_BRANCH_NAME)"
        ../../../io -v
